### ISSUE TITLE
ajax POST wrong address

### ISSUE THREAD

**Issue by Summer88** [stefangabos/zebrajs#1]
Hi,
Thanks for sharing this beautiful and light library!
I'm triyng to send a POST request with ajax, but it seems something goes wrong.

```
function send(){
var address = 'http://ip/path/thepage.php?a=b';
$.ajax({
    url: address,
     method: 'POST',
     data: {
         a:b,
         bar: 'bax'
     }
 });
```
looking at console:

> zebra.js:1 POST http://ip/path/[object%20Object] net::ERR_EMPTY_RESPONSE

the page has been replaced by this [object%20Object], or am I missing something?
Thanks, BR

**Comment by stefangabos** [comment]
Should be fixed now. Thanks!

**Comment by Summer88** [comment]
Now it works, thanks for fast fix!
Have a nice day
