### ISSUE TITLE
Customised build error

### ISSUE THREAD

**Issue by thephoton** [stefangabos/zebrajs#2]
Hi - love zebra, just what I'm looking for!

There is a bug in the selector regex in the customised build version _only_:
`if (selector.match(/^\#[^\s]+$/)) elements.push(parent.getElementById(selector.substr(1)));`

in the customiser, this gets generated as:
`t.match(/^#[^s]+$/))`

the s needs escaping:
`t.match(/^#[^\s]+$/))`

Interestingly, the full minified version doesn't have this bug!

Thanks, keep up the good work.

**Comment by stefangabos** [comment]
Thank you!
